### ISSUE TITLE
Version 0.2.0 - Roadmap

### ISSUE THREAD

**Issue by SamBrishes** [pytesNET/snicker#11]
Hellow,

I just leave my todo list for the next major release here. There **MAY** also be a buyable PRO version, which will be equipped with a few extra features (but that isn't a promise ;)).

### Version 0.2.0

- [ ] Google's reCaptcha implementation
- [ ] A new "Basic" called template
- [ ] Spam and Timeout protection
- [ ] A few additional functions for (theme) developers
- [ ] A comment form on the backend to allow authors / admins to comment directly
- [ ] A popup to open the complete comment without switching to the "edit" page

### Version 0.2.0 [Pro]

- [ ] Auto-Updater (Get the latest Pro Edition)
- [ ] Auto-Backup System (Backup the comments automatically)
- [ ] The Author / Admin can favorite comments (which gets shown on the top)
- [ ] Show Tabs with "Newest", "Latest" and "Best-Rated" comments
- [ ] Show all "need to be moderated" comments for authors / admins on the frontend

If you've any suggestion leave a comment below! Thanks.

Sincerely,
Sam.

**Comment by dignajar** [comment]
You did a great job, also I really like the UI for the settings!

**Comment by SamBrishes** [comment]
Thanks :D

**Comment by dimobelov** [comment]
Wow, great. Can you add image free avatar option? Simple avatar from name. Some example here https://codepen.io/dimobelov/pen/BRmmjO

**Comment by SamBrishes** [comment]
Jup, that should be possible

**Comment by Joduai** [comment]
@dimobelov 
I was thinking about same feature. But in a simpler manner without javascript. Just getting first username letters (or first+last with 1 word nickname) within template and style it with css.

@SamBrishes  two questions:
1. will you enable all possible avatar options for gravatar?
2. I was thinking about creating an additional theme, but you added a theme system on todo.
Do you mean something like twig?

**Comment by SamBrishes** [comment]
Hellow,

1. Oops, I guess I missed the retro, robohash and blank fallback avatars for gravatar...  I'll add them too of course.

2. No, I don't want to add a complete templating engine Just for the comments. The theme support will just allow template developers to include an own Comments theme class. (But the current theme system will be easified as best as possible.)

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

Short Information about Google's reCaptcha (in a GDPR conform way). I was thinking how to embed this library without getting in privary-policy trouble and I guess there are only 4 ways (okay 3, the first one only counts for GDPR-less countries):

#### Embed reCaptcha directly [NOT GDPR CONFORM]
The JavaScript library will be directly added in the header of the theme. This may shouldn't be used within Europe, because it doesn't fulfill the GDPR requirements.

#### Embed reCaptcha using a global JS function (requires to adapt the theme / add JS on your own)
You can create a respective JavaScript alert box or dialog or whatever which asks the user for this permissions. If he accepts, you can easily call the 'snicker_load_reCaptcha()' function which will load the respective library for you.

#### Embed reCaptcha using a Cookie (requires to code an own function, which sets this cookie)
Almost the same as the option above, but also workable for disabled JS environments. So you can ask the user for his permissions and instead of using the global JavaScript function, you can simple reload the page, set the cookie and let the script load.

#### Embed reCaptcha using [the Cookie Consent Plugin](https://plugins.bludit.com/plugin/cookie-consent) by Frédéric K (@Fred89)
I couldn't found any real GDPR plugin, but I guess it shouldn't be a problem to use the Cookie Consent system if you adapt the text in the respective way.

![reCaptcha](https://user-images.githubusercontent.com/31392477/55533605-210a4780-56b2-11e9-958c-b35917ccd7ec.PNG)

Sincerely,
Sam.

**Comment by Joduai** [comment]
Did you think about using recaptcha3 as well a basic antispam, as it returns a value not a challenge?
Bludit has a function to block user from logging into /admin after he fails to provide right credentials fixed amount of time (5 or 10 by default - don't remember now). If this method could be used along with recaptcha3, you could prevent showing the form to those probably marked as spammers and bots.
Not that you wouldn't come up with own shadowban solution ;)
But for "normal" visitors recaptcha3 would be transparent like recaptcha2 using badge option.

I didn't dig for info what sort of user data does recaptcha3 collect. But comparing to v2 it shouldn't rely that much on user's hardware.

2 caveats I see
1. user should have a dropdown to set the min. level for marking reply as spam
2. I have no idea how recaptcha3 behaves with all privacy nabled options in browser along with eventual adblocks. With v2 I had to set some permissions, otherwise I wouldn't ever get through v2 challenge.

This would surely need some testing.

**Comment by julia-r** [comment]
I like that there is currently an option to disable captchas! Even better would be, when in this case the JS files from Google were not loaded at all.
